version: "3.8"

services:
  db:
    container_name: managerglass
    image: postgres:14-alpine
    restart: always
    user: postgres  # importante definir o usuário
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=postgres  # senha padrão
      - POSTGRES_USER=postgres  # usuário padrão
      - POSTGRES_DB=managerglass  # necessário porque foi configurado assim no settings
    ports:
      - 5433:5432  # repare na porta externa 5433
    networks:
      - managerglass

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: managerglass_app
    hostname: app
    stdin_open: true
    expose:
      - '8000'
    volumes:
      - .env.js:/app/.env.js
      - /tmp:/tmp
    command: bash -c "gunicorn backend.wsgi:application -b 0.0.0.0:8000"
    depends_on:
      - db
    networks:
      - managerglass

  nginx:
    container_name: managerglass_nginx
    image: nginx
    hostname: nginx
    ports:
      - '80:8000'
      - '443:443'
    volumes:
      - ./docker/proxy/nginx/:/etc/nginx/conf.d/
      # - ./certbot/conf:/etc/nginx/ssl
      # - ./certbot/data:/usr/share/nginx/html/letsencrypt
      # - ./certbot/conf:/etc/letsencrypt
      # - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - managerglass

  certbot:
    image: certbot/certbot
    command: certonly --webroot -w /var/www/certbot --email regis42santos@gmail.com -d managerglass.com.br --agree-tos
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  pgadmin:
    container_name: managerglass_pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    volumes:
       - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 5050:80
    networks:
      - managerglass

  mailhog:
    container_name: managerglass_mailhog
    image: mailhog/mailhog
    restart: always
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - managerglass

volumes:
  pgdata:
  pgadmin:
  certbot:

networks:
  managerglass: